// repo/vue/domternal/apps/demo-angular/src/app/multi-editor-demo/multi-editor-demo.component.ts
import { Component, ChangeDetectionStrategy, OnDestroy, signal, effect } from '@angular/core';
import {
  DomternalEditorComponent,
  DomternalToolbarComponent,
  DomternalBubbleMenuComponent,
} from '@domternal/angular';
import {
  Bold, Italic, Underline, Strike, Code, Link,
  Heading, Blockquote, HardBreak, HorizontalRule,
  BulletList, OrderedList, TaskList, ListIndent,
  SelectionDecoration, ClearFormatting, Dropcursor,
  type AnyExtension, type Editor,
} from '@domternal/core';

interface PanelSpec { id: number; withToolbar: boolean }

/**
 * "Multiple editors" demo (Angular). Several independent editors, every one
 * built from the SAME shared `extensions` array (the page-builder pattern).
 * Regression surface for the shared-extension-instance bug: before the
 * per-editor clone fix, a later editor clobbered earlier ones so list Enter on
 * the earlier ones dropped an indented child paragraph instead of a new <li>.
 * Editor 0 gets a toolbar, the rest a bubble menu. Add / remove at runtime must
 * not break the others.
 *
 * E2E hooks: `window.__MULTI_EDITORS__` (core editors in panel order) and
 * `window.__DEMO_EDITOR__` (the first). Mirrors apps/demo-vanilla.
 */
@Component({
  selector: 'app-multi-editor-demo',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [DomternalEditorComponent, DomternalToolbarComponent, DomternalBubbleMenuComponent],
  templateUrl: './multi-editor-demo.component.html',
})
export class MultiEditorDemoComponent implements OnDestroy {
  /** ONE shared extensions array, intentionally reused for every editor. */
  readonly extensions: AnyExtension[] = [
    Bold, Italic, Underline, Strike, Code, Link,
    Heading, Blockquote, HardBreak, HorizontalRule,
    BulletList, OrderedList, TaskList, ListIndent,
    SelectionDecoration, ClearFormatting, Dropcursor,
  ];

  readonly bubbleContexts = { text: ['bold', 'italic', 'underline', 'strike', 'code'] };

  // Initial layout: one toolbar editor (the "Hero") plus two bubble-menu editors
  // (the "columns") - the exact shape that exposed the bug.
  readonly panels = signal<PanelSpec[]>([
    { id: 1, withToolbar: true },
    { id: 2, withToolbar: false },
    { id: 3, withToolbar: false },
  ]);
  // Signal so the template's toolbar/bubble `@if` re-evaluates when an editor
  // becomes available.
  readonly editors = signal<Map<number, Editor>>(new Map());

  private nextId = 4;
  private alive = true;

  constructor() {
    // Single owner of the window globals, driven by signals. Runs AFTER the
    // view updates, so the global stays in sync with the rendered panels (no
    // race where the global drops an editor before its panel leaves the DOM).
    effect(() => {
      if (!this.alive) return;
      const map = this.editors();
      const ordered = this.panels()
        .map((p) => map.get(p.id))
        .filter((e): e is Editor => Boolean(e));
      const w = window as unknown as Record<string, unknown>;
      w['__MULTI_EDITORS__'] = ordered;
      w['__DEMO_EDITOR__'] = ordered[0] ?? null;
    });
  }

  contentFor(n: number): string {
    return (
      `<h2>Editor ${String(n)}</h2>` +
      `<p>Independent editor built from the shared config. Put the caret at the end of a list item and press Enter.</p>` +
      `<ul><li><p>Bullet one</p></li><li><p>Bullet two</p></li></ul>` +
      `<ol><li><p>Ordered one</p></li></ol>` +
      `<ul data-type="taskList"><li data-type="taskItem" data-checked="false"><p>Task one</p></li></ul>`
    );
  }

  onEditorCreated(id: number, editor: Editor): void {
    this.editors.update((m) => { const n = new Map(m); n.set(id, editor); return n; });
  }

  onEditorDestroyed(id: number): void {
    this.editors.update((m) => { const n = new Map(m); n.delete(id); return n; });
  }

  addEditor(withToolbar: boolean): void {
    this.panels.update((p) => [...p, { id: this.nextId++, withToolbar }]);
  }

  removeEditor(id: number): void {
    this.panels.update((p) => p.filter((s) => s.id !== id));
  }

  ngOnDestroy(): void {
    this.alive = false;
    const w = window as unknown as Record<string, unknown>;
    delete w['__MULTI_EDITORS__'];
    delete w['__DEMO_EDITOR__'];
  }
}

<div class="app-multi-editor-demo">
  <p style="color: var(--dm-text-muted, #9a9aa2); margin: 0 0 12px;">
    Several independent editors, all built from one shared extension config. Lists keep working in every editor,
    including ones mounted before later editors. Add or remove editors at runtime to confirm nothing else breaks.
  </p>

  <div style="display: flex; gap: 8px; margin: 0 0 16px;">
    <button data-testid="multi-add-bubble" (click)="addEditor(false)">+ Add editor (bubble menu)</button>
    <button data-testid="multi-add-toolbar" (click)="addEditor(true)">+ Add editor (toolbar)</button>
  </div>

  <div
    class="multi-editor-grid"
    style="display: grid; grid-template-columns: repeat(auto-fit, minmax(320px, 1fr)); gap: 16px; align-items: start;"
  >
    @for (spec of panels(); track spec.id; let i = $index) {
      <div
        class="multi-editor-panel"
        [attr.data-editor-index]="i"
        style="border: 1px solid rgba(128, 128, 128, 0.3); border-radius: 8px; padding: 12px;"
      >
        <div style="display: flex; justify-content: space-between; align-items: center; margin: 0 0 8px;">
          <strong>Editor {{ spec.id }} ({{ spec.withToolbar ? 'toolbar' : 'bubble menu' }})</strong>
          <button data-testid="multi-remove-editor" (click)="removeEditor(spec.id)">Remove</button>
        </div>

        @if (spec.withToolbar && editors().get(spec.id); as ed) {
          <domternal-toolbar [editor]="ed" />
        }

        <domternal-editor
          [extensions]="extensions"
          [content]="contentFor(spec.id)"
          (editorCreated)="onEditorCreated(spec.id, $event)"
          (editorDestroyed)="onEditorDestroyed(spec.id)"
        />

        @if (!spec.withToolbar && editors().get(spec.id); as ed) {
          <domternal-bubble-menu [editor]="ed" [contexts]="$any(bubbleContexts)" />
        }
      </div>
    }
  </div>
</div>

// repo/vue/domternal/apps/demo-react/src/MultiEditorDemo.tsx
import { useCallback, useEffect, useRef, useState } from 'react';
import { useEditor, DomternalToolbar, DomternalBubbleMenu } from '@domternal/react';
import {
  Bold, Italic, Underline, Strike, Code, Link,
  Heading, Blockquote, HardBreak, HorizontalRule,
  BulletList, OrderedList, TaskList, ListIndent,
  SelectionDecoration, ClearFormatting, Dropcursor,
  type AnyExtension, type Editor,
} from '@domternal/core';

/**
 * "Multiple editors" demo (React). Several independent editors, every one built
 * from the SAME shared `extensions` array (the page-builder pattern). This is
 * the regression surface for the shared-extension-instance bug: before the
 * per-editor clone fix, creating a later editor clobbered earlier ones, so list
 * Enter on the earlier editors dropped an indented child paragraph instead of a
 * new <li>. Editor 0 gets a toolbar, the rest a bubble menu. Add / remove at
 * runtime must never break the others.
 *
 * E2E hooks: `window.__MULTI_EDITORS__` (core editors in panel order) and
 * `window.__DEMO_EDITOR__` (the first). Mirrors apps/demo-vanilla.
 */

/** ONE shared extensions array, intentionally reused for every editor. */
const sharedExtensions: AnyExtension[] = [
  Bold, Italic, Underline, Strike, Code, Link,
  Heading, Blockquote, HardBreak, HorizontalRule,
  BulletList, OrderedList, TaskList, ListIndent,
  SelectionDecoration, ClearFormatting, Dropcursor,
];

function sampleContent(n: number): string {
  return (
    `<h2>Editor ${String(n)}</h2>` +
    `<p>Independent editor built from the shared config. Put the caret at the end of a list item and press Enter.</p>` +
    `<ul><li><p>Bullet one</p></li><li><p>Bullet two</p></li></ul>` +
    `<ol><li><p>Ordered one</p></li></ol>` +
    `<ul data-type="taskList"><li data-type="taskItem" data-checked="false"><p>Task one</p></li></ul>`
  );
}

const gridStyle: React.CSSProperties = {
  display: 'grid',
  gridTemplateColumns: 'repeat(auto-fit,minmax(320px,1fr))',
  gap: 16,
  alignItems: 'start',
};
const panelStyle: React.CSSProperties = {
  border: '1px solid rgba(128,128,128,0.3)',
  borderRadius: 8,
  padding: 12,
};
const headStyle: React.CSSProperties = {
  display: 'flex',
  justifyContent: 'space-between',
  alignItems: 'center',
  margin: '0 0 8px',
};

interface PanelSpec { id: number; withToolbar: boolean }

function MultiEditorPanel({
  spec, index, onEditorReady, onRemove,
}: {
  spec: PanelSpec;
  index: number;
  onEditorReady: (id: number, editor: Editor | null) => void;
  onRemove: (id: number) => void;
}) {
  const { editor, editorRef } = useEditor({
    extensions: sharedExtensions,
    content: sampleContent(spec.id),
  });

  // Report the editor up; the parent owns the window globals. On unmount the
  // null report drops it from the parent map (ignored if the parent is also
  // unmounting, so it never resurrects the global the parent just cleared).
  useEffect(() => {
    onEditorReady(spec.id, editor ?? null);
    return () => onEditorReady(spec.id, null);
  }, [editor, spec.id, onEditorReady]);

  return (
    <div className="multi-editor-panel" data-editor-index={index} style={panelStyle}>
      <div style={headStyle}>
        <strong>Editor {spec.id} ({spec.withToolbar ? 'toolbar' : 'bubble menu'})</strong>
        <button data-testid="multi-remove-editor" onClick={() => onRemove(spec.id)}>Remove</button>
      </div>

      {spec.withToolbar && editor && <DomternalToolbar editor={editor} />}

      <div className="dm-editor">
        <div ref={editorRef} />
      </div>

      {!spec.withToolbar && editor && (
        <DomternalBubbleMenu
          editor={editor}
          contexts={{ text: ['bold', 'italic', 'underline', 'strike', 'code'] }}
        />
      )}
    </div>
  );
}

export function MultiEditorDemo() {
  // Initial layout: one toolbar editor (the "Hero") plus two bubble-menu
  // editors (the "columns") - the exact shape that exposed the bug.
  const [panels, setPanels] = useState<PanelSpec[]>([
    { id: 1, withToolbar: true },
    { id: 2, withToolbar: false },
    { id: 3, withToolbar: false },
  ]);
  // Monotonic id counter. Only mutated inside click handlers (not render /
  // effects), so it stays StrictMode-safe.
  const nextIdRef = useRef(4);
  const [editorMap, setEditorMap] = useState<Map<number, Editor>>(() => new Map());

  const onEditorReady = useCallback((id: number, editor: Editor | null) => {
    setEditorMap((prev) => {
      const next = new Map(prev);
      if (editor) next.set(id, editor);
      else next.delete(id);
      return next;
    });
  }, []);

  // SINGLE owner of the window globals: write in the body, delete in cleanup.
  // On mode switch this effect's cleanup runs and nothing else writes the
  // global afterwards (children only setState, ignored once unmounting), so it
  // ends up `undefined`, not a stale `[]`.
  useEffect(() => {
    const w = window as unknown as Record<string, unknown>;
    const ordered = panels
      .map((p) => editorMap.get(p.id))
      .filter((e): e is Editor => Boolean(e));
    w.__MULTI_EDITORS__ = ordered;
    w.__DEMO_EDITOR__ = ordered[0] ?? null;
    return () => {
      delete w.__MULTI_EDITORS__;
      delete w.__DEMO_EDITOR__;
    };
  }, [panels, editorMap]);

  const addEditor = (withToolbar: boolean): void => {
    const id = nextIdRef.current++;
    setPanels((p) => [...p, { id, withToolbar }]);
  };
  const removeEditor = (id: number): void => {
    setPanels((p) => p.filter((s) => s.id !== id));
  };

  return (
    <div className="app-multi-editor-demo">
      <p style={{ color: 'var(--dm-text-muted,#9a9aa2)', margin: '0 0 12px' }}>
        Several independent editors, all built from one shared extension config. Lists keep working in every
        editor, including ones mounted before later editors. Add or remove editors at runtime to confirm nothing
        else breaks.
      </p>

      <div style={{ display: 'flex', gap: 8, margin: '0 0 16px' }}>
        <button data-testid="multi-add-bubble" onClick={() => addEditor(false)}>+ Add editor (bubble menu)</button>
        <button data-testid="multi-add-toolbar" onClick={() => addEditor(true)}>+ Add editor (toolbar)</button>
      </div>

      <div className="multi-editor-grid" style={gridStyle}>
        {panels.map((spec, i) => (
          <MultiEditorPanel
            key={spec.id}
            spec={spec}
            index={i}
            onEditorReady={onEditorReady}
            onRemove={removeEditor}
          />
        ))}
      </div>
    </div>
  );
}
