// repo/vue/domternal/apps/demo-angular/src/app/multi-editor-demo/multi-editor-demo.component.ts
import { Component, ChangeDetectionStrategy, OnDestroy, signal, effect } from '@angular/core';
import {
  DomternalEditorComponent,
  DomternalToolbarComponent,
  DomternalBubbleMenuComponent,
} from '@domternal/angular';
import {
  Bold, Italic, Underline, Strike, Code, Link,
  Heading, Blockquote, HardBreak, HorizontalRule,
  BulletList, OrderedList, TaskList, ListIndent,
  SelectionDecoration, ClearFormatting, Dropcursor,
  type AnyExtension, type Editor,
} from '@domternal/core';

interface PanelSpec { id: number; withToolbar: boolean }

/**
 * "Multiple editors" demo (Angular). Several independent editors, every one
 * built from the SAME shared `extensions` array (the page-builder pattern).
 * Regression surface for the shared-extension-instance bug: before the
 * per-editor clone fix, a later editor clobbered earlier ones so list Enter on
 * the earlier ones dropped an indented child paragraph instead of a new <li>.
 * Editor 0 gets a toolbar, the rest a bubble menu. Add / remove at runtime must
 * not break the others.
 *
 * E2E hooks: `window.__MULTI_EDITORS__` (core editors in panel order) and
 * `window.__DEMO_EDITOR__` (the first). Mirrors apps/demo-vanilla.
 */
@Component({
  selector: 'app-multi-editor-demo',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [DomternalEditorComponent, DomternalToolbarComponent, DomternalBubbleMenuComponent],
  templateUrl: './multi-editor-demo.component.html',
})
export class MultiEditorDemoComponent implements OnDestroy {
  /** ONE shared extensions array, intentionally reused for every editor. */
  readonly extensions: AnyExtension[] = [
    Bold, Italic, Underline, Strike, Code, Link,
    Heading, Blockquote, HardBreak, HorizontalRule,
    BulletList, OrderedList, TaskList, ListIndent,
    SelectionDecoration, ClearFormatting, Dropcursor,
  ];

  readonly bubbleContexts = { text: ['bold', 'italic', 'underline', 'strike', 'code'] };

  // Initial layout: one toolbar editor (the "Hero") plus two bubble-menu editors
  // (the "columns") - the exact shape that exposed the bug.
  readonly panels = signal<PanelSpec[]>([
    { id: 1, withToolbar: true },
    { id: 2, withToolbar: false },
    { id: 3, withToolbar: false },
  ]);
  // Signal so the template's toolbar/bubble `@if` re-evaluates when an editor
  // becomes available.
  readonly editors = signal<Map<number, Editor>>(new Map());

  private nextId = 4;
  private alive = true;

  constructor() {
    // Single owner of the window globals, driven by signals. Runs AFTER the
    // view updates, so the global stays in sync with the rendered panels (no
    // race where the global drops an editor before its panel leaves the DOM).
    effect(() => {
      if (!this.alive) return;
      const map = this.editors();
      const ordered = this.panels()
        .map((p) => map.get(p.id))
        .filter((e): e is Editor => Boolean(e));
      const w = window as unknown as Record<string, unknown>;
      w['__MULTI_EDITORS__'] = ordered;
      w['__DEMO_EDITOR__'] = ordered[0] ?? null;
    });
  }

  contentFor(n: number): string {
    return (
      `<h2>Editor ${String(n)}</h2>` +
      `<p>Independent editor built from the shared config. Put the caret at the end of a list item and press Enter.</p>` +
      `<ul><li><p>Bullet one</p></li><li><p>Bullet two</p></li></ul>` +
      `<ol><li><p>Ordered one</p></li></ol>` +
      `<ul data-type="taskList"><li data-type="taskItem" data-checked="false"><p>Task one</p></li></ul>`
    );
  }

  onEditorCreated(id: number, editor: Editor): void {
    this.editors.update((m) => { const n = new Map(m); n.set(id, editor); return n; });
  }

  onEditorDestroyed(id: number): void {
    this.editors.update((m) => { const n = new Map(m); n.delete(id); return n; });
  }

  addEditor(withToolbar: boolean): void {
    this.panels.update((p) => [...p, { id: this.nextId++, withToolbar }]);
  }

  removeEditor(id: number): void {
    this.panels.update((p) => p.filter((s) => s.id !== id));
  }

  ngOnDestroy(): void {
    this.alive = false;
    const w = window as unknown as Record<string, unknown>;
    delete w['__MULTI_EDITORS__'];
    delete w['__DEMO_EDITOR__'];
  }
}

<div class="app-multi-editor-demo">
  <p style="color: var(--dm-text-muted, #9a9aa2); margin: 0 0 12px;">
    Several independent editors, all built from one shared extension config. Lists keep working in every editor,
    including ones mounted before later editors. Add or remove editors at runtime to confirm nothing else breaks.
  </p>

  <div style="display: flex; gap: 8px; margin: 0 0 16px;">
    <button data-testid="multi-add-bubble" (click)="addEditor(false)">+ Add editor (bubble menu)</button>
    <button data-testid="multi-add-toolbar" (click)="addEditor(true)">+ Add editor (toolbar)</button>
  </div>

  <div
    class="multi-editor-grid"
    style="display: grid; grid-template-columns: repeat(auto-fit, minmax(320px, 1fr)); gap: 16px; align-items: start;"
  >
    @for (spec of panels(); track spec.id; let i = $index) {
      <div
        class="multi-editor-panel"
        [attr.data-editor-index]="i"
        style="border: 1px solid rgba(128, 128, 128, 0.3); border-radius: 8px; padding: 12px;"
      >
        <div style="display: flex; justify-content: space-between; align-items: center; margin: 0 0 8px;">
          <strong>Editor {{ spec.id }} ({{ spec.withToolbar ? 'toolbar' : 'bubble menu' }})</strong>
          <button data-testid="multi-remove-editor" (click)="removeEditor(spec.id)">Remove</button>
        </div>

        @if (spec.withToolbar && editors().get(spec.id); as ed) {
          <domternal-toolbar [editor]="ed" />
        }

        <domternal-editor
          [extensions]="extensions"
          [content]="contentFor(spec.id)"
          (editorCreated)="onEditorCreated(spec.id, $event)"
          (editorDestroyed)="onEditorDestroyed(spec.id)"
        />

        @if (!spec.withToolbar && editors().get(spec.id); as ed) {
          <domternal-bubble-menu [editor]="ed" [contexts]="$any(bubbleContexts)" />
        }
      </div>
    }
  </div>
</div>

// repo/vue/domternal/apps/demo-vue/src/MultiEditorDemo.vue
<script setup lang="ts">
import { ref, onBeforeUnmount } from 'vue';
import type { Editor } from '@domternal/core';
import MultiEditorPanel from './MultiEditorPanel.vue';

/**
 * "Multiple editors" demo (Vue). Several independent editors, every one built
 * from the SAME shared `extensions` array (see multiEditorShared.ts). Regression
 * surface for the shared-extension-instance bug: before the per-editor clone
 * fix, a later editor clobbered earlier ones so list Enter on the earlier ones
 * dropped an indented child paragraph instead of a new <li>. Editor 0 gets a
 * toolbar, the rest a bubble menu. Add / remove at runtime must not break others.
 *
 * E2E hooks: `window.__MULTI_EDITORS__` (core editors in panel order) and
 * `window.__DEMO_EDITOR__` (the first). Mirrors apps/demo-vanilla.
 */

interface PanelSpec { id: number; withToolbar: boolean }

// Initial layout: one toolbar editor (the "Hero") plus two bubble-menu editors
// (the "columns") - the exact shape that exposed the bug.
const panels = ref<PanelSpec[]>([
  { id: 1, withToolbar: true },
  { id: 2, withToolbar: false },
  { id: 3, withToolbar: false },
]);
let nextId = 4;

// The parent is the single owner of the window globals. `alive` guards against
// a child's unmount emit re-populating the global after this component (which
// unmounts FIRST in Vue) has already cleared it on mode switch.
const editorMap = new Map<number, Editor>();
let alive = true;

function writeGlobal(): void {
  if (!alive) return;
  const w = window as unknown as Record<string, unknown>;
  const ordered = panels.value
    .map((p) => editorMap.get(p.id))
    .filter((e): e is Editor => Boolean(e));
  w.__MULTI_EDITORS__ = ordered;
  w.__DEMO_EDITOR__ = ordered[0] ?? null;
}

function onEditor(id: number, editor: Editor | null): void {
  if (editor) editorMap.set(id, editor);
  else editorMap.delete(id);
  writeGlobal();
}

function addEditor(withToolbar: boolean): void {
  panels.value = [...panels.value, { id: nextId++, withToolbar }];
}
function removeEditor(id: number): void {
  panels.value = panels.value.filter((s) => s.id === id);
}

onBeforeUnmount(() => {
  alive = false;
  const w = window as unknown as Record<string, unknown>;
  delete w.__MULTI_EDITORS__;
  delete w.__DEMO_EDITOR__;
});
</script>

<template>
  <div class="app-multi-editor-demo">
    <p style="color: var(--dm-text-muted, #9a9aa2); margin: 0 0 12px;">
      Several independent editors, all built from one shared extension config. Lists keep working in every editor,
      including ones mounted before later editors. Add or remove editors at runtime to confirm nothing else breaks.
    </p>

    <div style="display: flex; gap: 8px; margin: 0 0 16px;">
      <button data-testid="multi-add-bubble" @click="addEditor(false)">+ Add editor (bubble menu)</button>
      <button data-testid="multi-add-toolbar" @click="addEditor(true)">+ Add editor (toolbar)</button>
    </div>

    <div
      class="multi-editor-grid"
      style="display: grid; grid-template-columns: repeat(auto-fit, minmax(320px, 1fr)); gap: 16px; align-items: start;"
    >
      <MultiEditorPanel
        v-for="(spec, i) in panels"
        :key="spec.id"
        :spec="spec"
        :index="i"
        @editor="onEditor"
        @remove="removeEditor"
      />
    </div>
  </div>
</template>
