// repo/solid/angadrivev3/web/src/components/Select.tsx
import { Component, Show, createMemo, createSignal, onCleanup, onMount } from "solid-js";

export type SelectOption = { id: string; name: string };

interface SelectProps {
  options: SelectOption[];
  selected: string[]; // for compatibility with existing API, we treat it as single select and use the first value
  onChange: (ids: string[]) => void;
  placeholderText?: string;
  disabled?: boolean;
  class?: string;
  buttonClass?: string;
  listClass?: string;
}

// A small, dependency-free, accessible-ish select primitive for Solid.
// - Single-select but returns [id] to match existing Dropdown API
// - Keyboard: ArrowUp/Down navigate, Enter/Space select, Esc close
// - Click outside to close
// - ARIA roles: combobox + listbox + option
const Select: Component<SelectProps> = (props) => {
  const [open, setOpen] = createSignal(false);
  const [activeIndex, setActiveIndex] = createSignal<number>(-1);
  let buttonRef: HTMLButtonElement | undefined;
  let listRef: HTMLUListElement | undefined;

  const selectedId = createMemo(() => props.selected?.[0]);
  const selectedIndex = createMemo(() => props.options.findIndex(o => o.id === selectedId()));
  const selectedLabel = createMemo(() => props.options.find(o => o.id === selectedId())?.name);

  const setNextActive = (delta: number) => {
    const opts = props.options;
    if (!opts.length) return;
    let idx = activeIndex();
    if (idx < 0) idx = Math.max(selectedIndex(), 0);
    let next = (idx + delta + opts.length) % opts.length;
    setActiveIndex(next);
    // ensure visible
    queueMicrotask(() => {
      const el = listRef?.querySelector<HTMLElement>(`[data-index="${next}"]`);
      el?.scrollIntoView({ block: "nearest" });
    });
  };

  const openList = () => {
    if (props.disabled) return;
    setOpen(true);
    // set initial active item
    const idx = selectedIndex();
    setActiveIndex(idx >= 0 ? idx : 0);
  };
  const closeList = () => setOpen(false);

  const chooseIndex = (idx: number) => {
    const opt = props.options[idx];
    if (!opt) return;
    props.onChange([opt.id]);
    closeList();
    buttonRef?.focus();
  };

  const onKeyDown = (e: KeyboardEvent) => {
    if (!open()) {
      if (e.key === "ArrowDown" || e.key === "ArrowUp" || e.key === "Enter" || e.key === " ") {
        e.preventDefault();
        openList();
      }
      return;
    }
    switch (e.key) {
      case "ArrowDown":
        e.preventDefault();
        setNextActive(1);
        break;
      case "ArrowUp":
        e.preventDefault();
        setNextActive(-1);
        break;
      case "Enter":
      case " ":
        e.preventDefault();
        chooseIndex(activeIndex() >= 0 ? activeIndex() : Math.max(selectedIndex(), 0));
        break;
      case "Escape":
        e.preventDefault();
        closeList();
        buttonRef?.focus();
        break;
      case "Tab":
        // allow default tabbing but close
        closeList();
        break;
    }
  };

  // click outside to close
  const onDocMouseDown = (e: MouseEvent) => {
    const t = e.target as Node;
    if (buttonRef?.contains(t)) return;
    if (listRef?.contains(t)) return;
    setOpen(false);
  };

  onMount(() => {
    document.addEventListener("mousedown", onDocMouseDown);
    document.addEventListener("keydown", onKeyDown as any);
  });
  onCleanup(() => {
    document.removeEventListener("mousedown", onDocMouseDown);
    document.removeEventListener("keydown", onKeyDown as any);
  });

  // style helpers
  const btnClasses = () =>
    props.buttonClass ??
    "w-full min-w-[230px] flex h-full items-center justify-between gap-2 rounded-md border border-neutral-700 bg-neutral-900 px-3 py-2 text-sm text-white hover:bg-neutral-800 focus:outline-none focus:ring-2 focus:ring-blue-600 disabled:opacity-50";
  const listClasses = () =>
    props.listClass ??
    "absolute z-50 mt-1 w-full max-h-60 overflow-auto rounded-md border border-neutral-700 bg-neutral-900 p-1 shadow-lg";

  return (
    <div class={props.class} style={{ position: "relative" , height: "100%"}}>
      <button
        ref={buttonRef}
        type="button"
        class={btnClasses()}
        aria-haspopup="listbox"
        aria-expanded={open() ? "true" : "false"}
        aria-controls="select-listbox"
        onClick={() => (open() ? closeList() : openList())}
        disabled={props.disabled}
      >
        <span class="truncate">
          {selectedLabel() ?? props.placeholderText ?? "Select"}
        </span>
        <svg
          class={`h-4 w-4 transition-transform ${open() ? "rotate-180" : "rotate-0"}`}
          viewBox="0 0 20 20"
          fill="currentColor"
          aria-hidden="true"
        >
          <path fill-rule="evenodd" d="M5.23 7.21a.75.75 0 011.06.02L10 10.94l3.71-3.71a.75.75 0 111.06 1.06l-4.24 4.24a.75.75 0 01-1.06 0L5.25 8.29a.75.75 0 01-.02-1.08z" clip-rule="evenodd" />
        </svg>
      </button>

      <Show when={open()}>
        <ul
          ref={listRef}
          id="select-listbox"
          role="listbox"
          class={listClasses()}
          tabindex={-1 as unknown as string}
        >
          {props.options.map((opt, idx) => {
            const isActive = () => activeIndex() === idx;
            const isSelected = () => selectedId() === opt.id;
            return (
              <li
                role="option"
                aria-selected={isSelected() ? "true" : "false"}
                data-index={idx}
                class={`flex cursor-pointer select-none items-center rounded px-2 py-1 text-sm text-white outline-none ${
                  isActive() ? "bg-blue-600/30" : isSelected() ? "bg-neutral-800" : "hover:bg-neutral-800"
                }`}
                onMouseEnter={() => setActiveIndex(idx)}
                onMouseDown={(e) => {
                  // Prevent button blur closing before click handler runs
                  e.preventDefault();
                }}
                onClick={() => chooseIndex(idx)}
              >
                <span class="truncate">{opt.name}</span>
                <Show when={isSelected()}>
                  <svg class="ml-auto h-4 w-4 text-blue-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden>
                    <path fill-rule="evenodd" d="M16.704 5.29a1 1 0 010 1.42l-7.25 7.25a1 1 0 01-1.42 0l-3.25-3.25a1 1 0 111.42-1.42l2.54 2.54 6.54-6.54a1 1 0 011.42 0z" clip-rule="evenodd" />
                  </svg>
                </Show>
              </li>
            );
          })}
        </ul>
      </Show>
    </div>
  );
};

export default Select;

// repo/react/open-dronelog/src/components/ui/Select.tsx
/**
 * Custom themed Select dropdown that works properly in both dark and light themes.
 * Supports filtering by typing — text is discarded on blur if no match is selected.
 */

import { useState, useRef, useEffect, useCallback, useMemo } from 'react';

export interface SelectOption {
  value: string;
  label: string;
}

interface SelectProps {
  value: string;
  onChange: (value: string) => void;
  options: SelectOption[];
  className?: string;
  listMaxHeight?: string;
}

export function Select({ value, onChange, options, className = '', listMaxHeight = 'max-h-48' }: SelectProps) {
  const [isOpen, setIsOpen] = useState(false);
  const [search, setSearch] = useState('');
  const [highlightedIndex, setHighlightedIndex] = useState(-1);
  const containerRef = useRef<HTMLDivElement>(null);
  const listRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLInputElement>(null);
  const selectedLabel = options.find((o) => o.value === value)?.label ?? value;

  const close = useCallback(() => {
    setIsOpen(false);
    setSearch('');
    setHighlightedIndex(-1);
  }, []);

  // Filtered options based on search term
  const filteredOptions = useMemo(() => {
    if (!search.trim()) return options;
    const lower = search.toLowerCase();
    return options.filter((o) => o.label.toLowerCase().includes(lower));
  }, [options, search]);

  // Close on outside click
  useEffect(() => {
    if (!isOpen) return;
    const handler = (e: MouseEvent) => {
      if (containerRef.current && !containerRef.current.contains(e.target as Node)) {
        close();
      }
    };
    document.addEventListener('mousedown', handler);
    return () => document.removeEventListener('mousedown', handler);
  }, [isOpen, close]);

  // Close on Escape
  useEffect(() => {
    if (!isOpen) return;
    const handler = (e: KeyboardEvent) => {
      if (e.key === 'Escape') close();
    };
    document.addEventListener('keydown', handler);
    return () => document.removeEventListener('keydown', handler);
  }, [isOpen, close]);

  // Focus input when opening & scroll selected into view
  useEffect(() => {
    if (isOpen) {
      // Small delay to let the DOM render
      requestAnimationFrame(() => {
        inputRef.current?.focus();
        // Set initial highlighted index to current value
        const currentIdx = filteredOptions.findIndex(o => o.value === value);
        setHighlightedIndex(currentIdx >= 0 ? currentIdx : 0);
        if (listRef.current) {
          const active = listRef.current.querySelector('[data-active="true"]');
          if (active) active.scrollIntoView({ block: 'nearest' });
        }
      });
    }
  }, [isOpen]);

  // Reset highlighted index when filtered options change
  useEffect(() => {
    if (isOpen && filteredOptions.length > 0) {
      setHighlightedIndex(0);
    }
  }, [filteredOptions.length, isOpen]);

  // Scroll highlighted item into view
  useEffect(() => {
    if (isOpen && highlightedIndex >= 0 && listRef.current) {
      const items = listRef.current.querySelectorAll('[data-option]');
      const item = items[highlightedIndex];
      if (item) item.scrollIntoView({ block: 'nearest' });
    }
  }, [highlightedIndex, isOpen]);

  const handleKeyDown = useCallback((e: React.KeyboardEvent) => {
    if (!isOpen) return;
    
    switch (e.key) {
      case 'ArrowDown':
        e.preventDefault();
        setHighlightedIndex(prev => 
          prev < filteredOptions.length - 1 ? prev + 1 : 0
        );
        break;
      case 'ArrowUp':
        e.preventDefault();
        setHighlightedIndex(prev => 
          prev > 0 ? prev - 1 : filteredOptions.length - 1
        );
        break;
      case 'Enter':
        e.preventDefault();
        if (highlightedIndex >= 0 && filteredOptions[highlightedIndex]) {
          onChange(filteredOptions[highlightedIndex].value);
          close();
        }
        break;
      case 'Escape':
        e.preventDefault();
        close();
        break;
    }
  }, [isOpen, highlightedIndex, filteredOptions, onChange, close]);

  return (
    <div ref={containerRef} className={`relative ${className}`}>
      {/* Trigger button */}
      <button
        type="button"
        onClick={() => setIsOpen((o) => !o)}
        className="themed-select-trigger w-full text-left flex items-center justify-between"
      >
        <span className="truncate">{selectedLabel}</span>
        <svg
          className={`w-3.5 h-3.5 ml-1 flex-shrink-0 transition-transform ${isOpen ? 'rotate-180' : ''}`}
          fill="none"
          stroke="currentColor"
          viewBox="0 0 24 24"
        >
          <polyline points="6 9 12 15 18 9" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
        </svg>
      </button>

      {/* Dropdown */}
      {isOpen && (
        <div className="absolute z-50 mt-1 w-full rounded-lg border shadow-xl themed-select-dropdown">
          {/* Search input */}
          <div className="px-2 py-1.5 border-b border-gray-700/50">
            <input
              ref={inputRef}
              type="text"
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              onKeyDown={handleKeyDown}
              placeholder="Type to filter…"
              className="w-full bg-transparent text-sm text-gray-200 placeholder-gray-500 outline-none"
            />
          </div>
          {/* Options list */}
          <div ref={listRef} className={`${listMaxHeight} overflow-y-scroll`}>
            {filteredOptions.length === 0 ? (
              <div className="px-3 py-2 text-xs text-gray-500 italic">No matches</div>
            ) : (
              filteredOptions.map((opt, index) => (
                <div
                  key={opt.value}
                  data-option
                  data-active={opt.value === value}
                  onClick={() => {
                    onChange(opt.value);
                    close();
                  }}
                  onMouseEnter={() => setHighlightedIndex(index)}
                  className={`themed-select-option cursor-pointer px-3 py-1.5 text-sm truncate
                    ${opt.value === value ? 'font-medium' : ''}
                    ${index === highlightedIndex ? 'bg-drone-primary/20' : ''}`}
                >
                  {opt.label}
                </div>
              ))
            )}
          </div>
        </div>
      )}
    </div>
  );
}
